import type { NextPage } from 'next'
import Head from 'next/head'
import Game from '../components/Game'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Game/>
      </main>

      <footer className={styles.footer}>
        <h3>
          Created by
        </h3>
      </footer>
    </div>
  )
}

export default Home
